### ISSUE TITLE
d3.timeParse is not a function

### ISSUE THREAD

**Issue by ASManojKumar** [d3/d3-time-format#69]
The same method was working in 2.2.1 version. 
Now after the new release it broke.

**Comment by mbostock** [comment]
Works fine for me. https://observablehq.com/d/089c31e40839c12a

Maybe try posting some code that reproduces the problem if you want help?

**Comment by ASManojKumar** [comment]
@mbostock d3.timeParse('%d/%m/%Y') this is failing.

**Comment by mbostock** [comment]
Still works fine for me. https://observablehq.com/d/089c31e40839c12a

You probably have some sort of bundling misconfiguration, and I can’t assist you in debugging that if you don’t share a reproduction of the problem.

**Comment by ASManojKumar** [comment]
![image](https://user-images.githubusercontent.com/12930893/69801453-4463a300-11fd-11ea-94b4-9966423b2721.png)

in the same observable, not I updated to d3.timeParse('%d-%m-%Y'), its giving as null.

**Comment by mbostock** [comment]
It returns null because the string you are passing the parser has slashed (`02/01/2001`) and the format you’ve specified expects dashes (`02-01-2001`). As the documentation says, if you pass a string that doesn’t match the format, the parser will return null.

You need to enable link sharing in the notebook menu for me to be able to see your notebook.

**Comment by ASManojKumar** [comment]
@mbostock yeah, just verified. Actually it throws d3.timeParse is not a function if buildOptimizer is set as true in angular.json file. if I make that as false, its working properly. So what can be the issue?

**Comment by mbostock** [comment]
It is a known issue that the Angular build optimizer breaks code. See angular/angular-cli#11439.

**Comment by dmc2015** [comment]
I don't see what the exact error message is here but I received:

```
  dataset.forEach(function(d) {
      d.month = d3.timeFormat("%Y-%m").parse(d.month);
  });
```

```
VM1504:1 Uncaught TypeError: d3.timeFormat(...).parse is not a function
    at eval (eval at <anonymous> (ui.self-56987c3c1a74e6646e1a6463849bc5c00e136e90db6d5ffc418f5a6f81c95ad0.js?body=1:1), <anonymous>:1:24)
    at ui.self-56987c3c1a74e6646e1a6463849bc5c00e136e90db6d5ffc418f5a6f81c95ad0.js?body=1:35
    at Array.forEach (<anonymous>)
    at timeLineVize (ui.self-56987c3c1a74e6646e1a6463849bc5c00e136e90db6d5ffc418f5a6f81c95ad0.js?body=1:34)
    at visual:315
eval @ VM1504:1
(anonymous) @ ui.self-56987c3c1a74e6646e1a6463849bc5c00e136e90db6d5ffc418f5a6f81c95ad0.js?body=1:35
timeLineVize @ ui.self-56987c3c1a74e6646e1a6463849bc5c00e136e90db6d5ffc418f5a6f81c95ad0.js?body=1:34
(anonymous) @ visual:315
```
The api has changed. For me the solution was:
var parseTime = d3.timeParse("%Y-%m")
parseTime("2018-09")

**Comment by Fil** [comment]
I don't think `d3.timeFormat(...).parse` was ever a thing. See https://github.com/d3/d3-time-format#locale_parse instead?
